### ISSUE TITLE
Thank you for creating this plugin :)

### ISSUE THREAD

**Issue by bradleyess** [xiaket/pipeline-linter-buildkite-plugin#1]
This would be very helpful to offer as a lightweight CLI that we could run pre-commit - would you be offended if I forked the repo to do that?

**Comment by xiaket** [comment]
Not at all, please do. Feel free to submit a PR as well :)

Glad you find this plugin helpful :)

**Comment by xiaket** [comment]
You know what, I'm going to create a Docker image for this, and hopefully you'll find that useful as well.

**Comment by xiaket** [comment]
Done with docker setup and I've tested locally. I'm going to close this. Hope you'll find the docker image helpful. And again, feel free to fork and contribute!  :)
